stages:
  data_loader:
    cmd: python src/data_loader.py
    outs:
      - data/raw/train.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw/train.csv
    outs:
      - data/processed/train_processed.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/processed/train_processed.csv
    outs:
      - data/interim/train_interim.csv

  model_building:
    cmd: python src/model_building.py
    deps:
      - src/model_building.py
      - data/interim/train_interim.csv
    outs:
      - models/lg/logistic_regression_model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - models/LG/logistic_regression_model.pkl
    outs:
      - reports/metrics.json
